#!/usr/bin/env bash
#
# Crea un repositorio en GitHub y sube este proyecto.
#
# Uso:
#   ./push-to-github.sh
#   ./push-to-github.sh --repo-name MiProyectoML --visibility private
#

set -euo pipefail

# -----------------------------------------------------------------------------
# Configuración por defecto
# -----------------------------------------------------------------------------
REPO_NAME="$(basename "$(pwd)")"
VISIBILITY="public"
CLEAN_TEMP_FILES=1

# -----------------------------------------------------------------------------
# Funciones auxiliares
# -----------------------------------------------------------------------------
print_step() {
    echo -e "\n\033[1;36m==> $1\033[0m"
}

print_success() {
    echo -e "\033[1;32m    ✔ $1\033[0m"
}

print_warning() {
    echo -e "\033[1;33m    ⚠ $1\033[0m"
}

print_error() {
    echo -e "\033[1;31m    ✖ $1\033[0m" >&2
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

show_help() {
    cat <<EOF
Uso: $0 [OPCIONES]

Opciones:
  -r, --repo-name NAME      Nombre del repositorio en GitHub (por defecto: carpeta actual)
  -v, --visibility TYPE     Visibilidad: public o private (por defecto: public)
  -c, --clean BOOL          Limpiar archivos temporales: 1 o 0 (por defecto: 1)
  -h, --help                Muestra esta ayuda

Ejemplos:
  $0
  $0 -r MiProyectoML -v private
EOF
}

# -----------------------------------------------------------------------------
# Procesar argumentos
# -----------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        -r|--repo-name)
            REPO_NAME="$2"
            shift 2
            ;;
        -v|--visibility)
            VISIBILITY="$2"
            if [[ "$VISIBILITY" != "public" && "$VISIBILITY" != "private" ]]; then
                print_error "La visibilidad debe ser 'public' o 'private'."
                exit 1
            fi
            shift 2
            ;;
        -c|--clean)
            CLEAN_TEMP_FILES="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            print_error "Opción desconocida: $1"
            show_help
            exit 1
            ;;
    esac
done

# -----------------------------------------------------------------------------
# 1. Verificar prerequisitos
# -----------------------------------------------------------------------------
print_step "Verificando prerequisitos..."

if ! command_exists git; then
    print_error "Git no está instalado o no se encuentra en el PATH. Descárgalo desde https://git-scm.com/downloads"
    exit 1
fi
print_success "Git encontrado."

if ! command_exists gh; then
    print_error "La CLI de GitHub (gh) no está instalada. Descárgala desde https://cli.github.com/"
    exit 1
fi
print_success "GitHub CLI (gh) encontrada."

if ! gh auth status >/dev/null 2>&1; then
    print_error "No estás autenticado en GitHub CLI. Ejecuta: gh auth login"
    exit 1
fi
print_success "Autenticado en GitHub CLI."

if [[ ! -f "AGENTS.md" ]]; then
    print_warning "No se encontró AGENTS.md en la carpeta actual. ¿Estás seguro de que este es el directorio raíz del proyecto?"
    read -rp "¿Continuar de todos modos? (s/N): " CONTINUE
    if [[ ! "$CONTINUE" =~ ^[sSyY]$ ]]; then
        exit 0
    fi
fi

# -----------------------------------------------------------------------------
# 2. Inicializar repositorio Git
# -----------------------------------------------------------------------------
print_step "Inicializando repositorio Git local..."

if [[ -d ".git" ]]; then
    print_warning "Ya existe un repositorio Git en esta carpeta. Se continuará con el remoto actual si existe."
else
    git init
    print_success "Repositorio Git inicializado."
fi

# -----------------------------------------------------------------------------
# 3. Configurar .gitignore y .gitattributes
# -----------------------------------------------------------------------------
print_step "Configurando .gitignore y .gitattributes..."

if [[ ! -f ".gitattributes" ]]; then
    cat > .gitattributes <<'EOF'
# Normalizar finales de línea
* text=auto
*.cs text eol=crlf
*.csproj text eol=crlf
*.sln text eol=crlf
*.py text eol=lf
*.ps1 text eol=crlf
*.sh text eol=lf
*.md text eol=lf
*.csv text eol=lf

# Archivos binarios
*.docx binary
*.xlsx binary
*.pbix binary
*.mlnet binary
*.zip binary
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.ico binary
EOF
    print_success "Archivo .gitattributes creado."
else
    print_warning "Ya existe un archivo .gitattributes. No se sobrescribió."
fi

if [[ ! -f ".gitignore" ]]; then
    cat > .gitignore <<'EOF'
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/

# Visual Studio cache/options directory
.vs/

# Visual Studio auto generated files
Generated\ Files/

# Files built by Visual Studio
*_i.c
*_p.c
*_h.h
*.ilk
*.meta
*.obj
*.iobj
*.pch
*.pdb
*.ipdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*_wpftmp.csproj
*.log
*.tlog
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc

# Visual C++ cache files
ipch/
*.aps
*.ncb
*.opendb
*.opensdf
*.sdf
*.cachefile
*.VC.db
*.VC.VC.opendb

# NuGet Packages
*.nupkg
*.snupkg
**/[Pp]ackages/*
!**/[Pp]ackages/build/
*.nuget.props
*.nuget.targets

# Others
ClientBin/
~$*
*~
*.dbmdl
*.dbproj.schemaview
*.jfm
*.pfx
*.publishsettings
orleans.codegen.cs

# Backup & report files from converting an old project file
_UpgradeReport_Files/
Backup*/
UpgradeLog*.XML
UpgradeLog*.htm
ServiceFabricBackup/
*.rptproj.bak

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
*.manifest
*.spec
pip-log.txt
pip-delete-this-directory.txt
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/
cover/
.ipynb_checkpoints
profile_default/
ipython_config.py
.python-version
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
.spyderproject
.spyproject
.ropeproject
/site
.mypy_cache/
.dmypy.json
dmypy.json
.pyre/
.pytype/
cython_debug/

# Archivos temporales y específicos de este proyecto
temp_docx/
extracted_text.txt
extracted_text_utf8.txt
desktop.ini
*.gdoc
*.zip
EOF
    print_success "Archivo .gitignore creado."
else
    print_warning "Ya existe un archivo .gitignore. No se sobrescribió."
fi

# -----------------------------------------------------------------------------
# 4. Limpiar archivos temporales
# -----------------------------------------------------------------------------
if [[ "$CLEAN_TEMP_FILES" == "1" ]]; then
    print_step "Limpiando archivos temporales..."
    ITEMS_TO_REMOVE=(
        "temp_docx"
        "extracted_text.txt"
        "extracted_text_utf8.txt"
        "desktop.ini"
        "Tarea_Prediccion_Ventas_MLNET_ModelBuilder.zip"
    )
    for ITEM in "${ITEMS_TO_REMOVE[@]}"; do
        if [[ -e "$ITEM" ]]; then
            rm -rf "$ITEM"
            print_success "Eliminado: $ITEM"
        fi
    done
fi

# -----------------------------------------------------------------------------
# 5. Crear repositorio en GitHub
# -----------------------------------------------------------------------------
print_step "Creando repositorio remoto en GitHub..."

if gh repo view "$REPO_NAME" >/dev/null 2>&1; then
    print_warning "El repositorio '$REPO_NAME' ya existe en GitHub."
    read -rp "¿Usar el repositorio existente? (s/N): " USE_EXISTING
    if [[ ! "$USE_EXISTING" =~ ^[sSyY]$ ]]; then
        exit 0
    fi
else
    gh repo create "$REPO_NAME" --"$VISIBILITY" --source=. --remote=origin --push
    print_success "Repositorio '$REPO_NAME' creado y configurado como remoto 'origin'."
fi

# -----------------------------------------------------------------------------
# 6. Agregar, commit y push
# -----------------------------------------------------------------------------
print_step "Preparando commit inicial..."

git add .
print_success "Archivos agregados al área de preparación."

if git diff --cached --quiet; then
    print_warning "No hay cambios para commitear."
else
    git commit -m "Initial commit" -m "Proyecto MLNETModelBuilder-PowerBI subido a GitHub."
    print_success "Commit inicial realizado."

    print_step "Subiendo cambios a GitHub..."
    BRANCH=$(git branch --show-current)
    git push -u origin "$BRANCH"
    print_success "Cambios subidos a la rama '$BRANCH'."
fi

# -----------------------------------------------------------------------------
# 7. Resumen final
# -----------------------------------------------------------------------------
echo -e "\n\033[1;32m========================================"
echo -e " ¡Listo! Repositorio subido a GitHub "
echo -e "========================================\033[0m"
REMOTE_URL=$(git remote get-url origin 2>/dev/null || true)
echo -e "URL remota: \033[1;37m$REMOTE_URL\033[0m"
echo -e "\n\033[1;36mPróximos pasos:\033[0m"
echo "  1. Revisa el repositorio en GitHub."
echo "  2. Conecta el modelo real de ML.NET en SalesPredictionApp."
echo "  3. Actualiza el README.md con la descripción del proyecto."
