#requires -Version 5.1
<#
.SYNOPSIS
    Crea un repositorio en GitHub y sube este proyecto.

.DESCRIPTION
    Este script inicializa el repositorio local, configura el .gitignore,
    limpia archivos temporales, crea el repositorio remoto en GitHub
    mediante la CLI 'gh' y realiza el push inicial.

.PARAMETER RepoName
    Nombre del repositorio en GitHub. Por defecto usa el nombre de la carpeta actual.

.PARAMETER Visibility
    Visibilidad del repositorio: 'public' o 'private'. Por defecto: public.

.PARAMETER CleanTempFiles
    Si es $true (por defecto), elimina archivos temporales antes del commit inicial.

.EXAMPLE
    .\push-to-github.ps1
    .\push-to-github.ps1 -RepoName "MiProyectoML" -Visibility private
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [string]$RepoName = (Split-Path -Leaf (Get-Location)),
    [ValidateSet("public", "private")]
    [string]$Visibility = "public",
    [bool]$CleanTempFiles = $true
)

$ErrorActionPreference = "Stop"

function Test-CommandExists {
    param([string]$Command)
    $null -ne (Get-Command $Command -ErrorAction SilentlyContinue)
}

function Write-Step {
    param([string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "    ✔ $Message" -ForegroundColor Green
}

function Write-WarningMsg {
    param([string]$Message)
    Write-Host "    ⚠ $Message" -ForegroundColor Yellow
}

# -----------------------------------------------------------------------------
# 1. Verificar prerequisitos
# -----------------------------------------------------------------------------
Write-Step "Verificando prerequisitos..."

if (-not (Test-CommandExists "git")) {
    Write-Error "Git no está instalado o no se encuentra en el PATH. Descárgalo desde https://git-scm.com/downloads"
}
Write-Success "Git encontrado."

if (-not (Test-CommandExists "gh")) {
    Write-Error "La CLI de GitHub (gh) no está instalada. Descárgala desde https://cli.github.com/"
}
Write-Success "GitHub CLI (gh) encontrada."

# Verificar autenticación con gh
$ghAuth = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "No estás autenticado en GitHub CLI. Ejecuta: gh auth login"
}
Write-Success "Autenticado en GitHub CLI."

# Verificar que estamos en la carpeta correcta
if (-not (Test-Path "AGENTS.md")) {
    Write-WarningMsg "No se encontró AGENTS.md en la carpeta actual. ¿Estás seguro de que este es el directorio raíz del proyecto?"
    $continue = Read-Host "¿Continuar de todos modos? (s/N)"
    if ($continue -notin @("s", "S", "si", "Si", "SI")) {
        exit 0
    }
}

# -----------------------------------------------------------------------------
# 2. Inicializar repositorio Git
# -----------------------------------------------------------------------------
Write-Step "Inicializando repositorio Git local..."

if (Test-Path ".git") {
    Write-WarningMsg "Ya existe un repositorio Git en esta carpeta. Se continuará con el remoto actual si existe."
}
else {
    if ($PSCmdlet.ShouldProcess(".", "git init")) {
        git init
        Write-Success "Repositorio Git inicializado."
    }
}

# -----------------------------------------------------------------------------
# 3. Configurar .gitignore y .gitattributes
# -----------------------------------------------------------------------------
Write-Step "Configurando .gitignore y .gitattributes..."

if (-not (Test-Path ".gitattributes")) {
    @"
# Normalizar finales de línea
* text=auto
*.cs text eol=crlf
*.csproj text eol=crlf
*.sln text eol=crlf
*.py text eol=lf
*.ps1 text eol=crlf
*.sh text eol=lf
*.md text eol=lf
*.csv text eol=lf

# Archivos binarios
*.docx binary
*.xlsx binary
*.pbix binary
*.mlnet binary
*.zip binary
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.ico binary
"@ | Out-File -Encoding utf8 ".gitattributes"
    Write-Success "Archivo .gitattributes creado."
}
else {
    Write-WarningMsg "Ya existe un archivo .gitattributes. No se sobrescribió."
}

if (-not (Test-Path ".gitignore")) {
    @"
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/

# Visual Studio cache/options directory
.vs/

# Visual Studio auto generated files
Generated\ Files/

# Files built by Visual Studio
*_i.c
*_p.c
*_h.h
*.ilk
*.meta
*.obj
*.iobj
*.pch
*.pdb
*.ipdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*_wpftmp.csproj
*.log
*.tlog
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc

# Visual C++ cache files
ipch/
*.aps
*.ncb
*.opendb
*.opensdf
*.sdf
*.cachefile
*.VC.db
*.VC.VC.opendb

# NuGet Packages
*.nupkg
*.snupkg
**/[Pp]ackages/*
!**/[Pp]ackages/build/
*.nuget.props
*.nuget.targets

# Others
ClientBin/
~$*
*~
*.dbmdl
*.dbproj.schemaview
*.jfm
*.pfx
*.publishsettings
orleans.codegen.cs

# Backup & report files from converting an old project file
_UpgradeReport_Files/
Backup*/
UpgradeLog*.XML
UpgradeLog*.htm
ServiceFabricBackup/
*.rptproj.bak

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
*.manifest
*.spec
pip-log.txt
pip-delete-this-directory.txt
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/
cover/
.ipynb_checkpoints
profile_default/
ipython_config.py
.python-version
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
.spyderproject
.spyproject
.ropeproject
/site
.mypy_cache/
.dmypy.json
dmypy.json
.pyre/
.pytype/
cython_debug/

# Archivos temporales y específicos de este proyecto
temp_docx/
extracted_text.txt
extracted_text_utf8.txt
desktop.ini
*.gdoc
*.zip
"@ | Out-File -Encoding utf8 ".gitignore"
    Write-Success "Archivo .gitignore creado."
}
else {
    Write-WarningMsg "Ya existe un archivo .gitignore. No se sobrescribió."
}

# -----------------------------------------------------------------------------
# 4. Limpiar archivos temporales
# -----------------------------------------------------------------------------
if ($CleanTempFiles) {
    Write-Step "Limpiando archivos temporales..."
    $itemsToRemove = @(
        "temp_docx",
        "extracted_text.txt",
        "extracted_text_utf8.txt",
        "desktop.ini",
        "Tarea_Prediccion_Ventas_MLNET_ModelBuilder.zip"
    )
    foreach ($item in $itemsToRemove) {
        if (Test-Path $item) {
            if ($PSCmdlet.ShouldProcess($item, "Remove-Item -Recurse -Force")) {
                Remove-Item -Path $item -Recurse -Force -ErrorAction SilentlyContinue
                Write-Success "Eliminado: $item"
            }
        }
    }
}

# -----------------------------------------------------------------------------
# 5. Crear repositorio en GitHub
# -----------------------------------------------------------------------------
Write-Step "Creando repositorio remoto en GitHub..."

$repoExists = gh repo view "$RepoName" 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-WarningMsg "El repositorio '$RepoName' ya existe en GitHub."
    $useExisting = Read-Host "¿Usar el repositorio existente? (s/N)"
    if ($useExisting -notin @("s", "S", "si", "Si", "SI")) {
        exit 0
    }
}
else {
    if ($PSCmdlet.ShouldProcess($RepoName, "gh repo create --$Visibility")) {
        gh repo create "$RepoName" --$Visibility --source=. --remote=origin --push
        if ($LASTEXITCODE -eq 0) {
            Write-Success "Repositorio '$RepoName' creado y configurado como remoto 'origin'."
        }
        else {
            Write-Error "No se pudo crear el repositorio en GitHub."
        }
    }
}

# -----------------------------------------------------------------------------
# 6. Agregar, commit y push
# -----------------------------------------------------------------------------
Write-Step "Preparando commit inicial..."

if ($PSCmdlet.ShouldProcess(".", "git add .")) {
    git add .
    Write-Success "Archivos agregados al área de preparación."
}

$hasChanges = git diff --cached --quiet
if ($LASTEXITCODE -ne 0) {
    if ($PSCmdlet.ShouldProcess(".", "git commit -m 'Initial commit'")) {
        git commit -m "Initial commit" -m "Proyecto MLNETModelBuilder-PowerBI subido a GitHub."
        Write-Success "Commit inicial realizado."
    }

    Write-Step "Subiendo cambios a GitHub..."
    if ($PSCmdlet.ShouldProcess("origin main", "git push")) {
        $branch = git branch --show-current
        git push -u origin "$branch"
        Write-Success "Cambios subidos a la rama '$branch'."
    }
}
else {
    Write-WarningMsg "No hay cambios para commitear."
}

# -----------------------------------------------------------------------------
# 7. Resumen final
# -----------------------------------------------------------------------------
Write-Host "`n========================================" -ForegroundColor Green
Write-Host " ¡Listo! Repositorio subido a GitHub " -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
$remoteUrl = git remote get-url origin 2>$null
Write-Host "URL remota: $remoteUrl" -ForegroundColor White
Write-Host "`nPróximos pasos:" -ForegroundColor Cyan
Write-Host "  1. Revisa el repositorio en GitHub."
Write-Host "  2. Conecta el modelo real de ML.NET en SalesPredictionApp."
Write-Host "  3. Actualiza el README.md con la descripción del proyecto."
