// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Transforms;

namespace SalesPredict
{
    public partial class SalesPredict
    {
        public const string RetrainFilePath =  @"G:\My Drive\estudios\ecotec\docencia\Modelos de Datos\MLNETModelBuilder-PowerBI\ventas_sinteticas_2025.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"category_name", @"category_name"),new InputOutputColumnPair(@"zone_name", @"zone_name")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"year_number", @"year_number"),new InputOutputColumnPair(@"month_number", @"month_number"),new InputOutputColumnPair(@"day_number", @"day_number"),new InputOutputColumnPair(@"day_of_week", @"day_of_week"),new InputOutputColumnPair(@"quantity", @"quantity"),new InputOutputColumnPair(@"unit_price", @"unit_price"),new InputOutputColumnPair(@"discount_percentage", @"discount_percentage")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"sale_id",outputColumnName:@"sale_id"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"sale_date",outputColumnName:@"sale_date"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"customer_code",outputColumnName:@"customer_code"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"customer_name",outputColumnName:@"customer_name"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"product_code",outputColumnName:@"product_code"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"product_name",outputColumnName:@"product_name"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"salesman_name",outputColumnName:@"salesman_name"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"warehouse_name",outputColumnName:@"warehouse_name"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"category_name",@"zone_name",@"year_number",@"month_number",@"day_number",@"day_of_week",@"quantity",@"unit_price",@"discount_percentage",@"sale_id",@"sale_date",@"customer_code",@"customer_name",@"product_code",@"product_name",@"salesman_name",@"warehouse_name"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=6076,NumberOfIterations=4273,MinimumExampleCountPerLeaf=20,LearningRate=0.9999997766729865,LabelColumnName=@"total_sales",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.11399600783512628,FeatureFraction=0.99999999,L1Regularization=3.809918619182013E-10,L2Regularization=0.1160661754740924},MaximumBinCountPerFeature=399}));

            return pipeline;
        }
    }
 }
