// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SalesPredictionApp
{
    public partial class SalesModel
    {
        /// <summary>
        /// model input class for SalesModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"sale_id")]
            public float Sale_id { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"sale_date")]
            public string Sale_date { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"year_number")]
            public float Year_number { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"month_number")]
            public float Month_number { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"day_number")]
            public float Day_number { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"day_of_week")]
            public float Day_of_week { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"customer_code")]
            public string Customer_code { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"customer_name")]
            public string Customer_name { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"product_code")]
            public string Product_code { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"product_name")]
            public string Product_name { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"category_name")]
            public string Category_name { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"zone_name")]
            public string Zone_name { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"salesman_name")]
            public string Salesman_name { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"warehouse_name")]
            public string Warehouse_name { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"quantity")]
            public float Quantity { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"unit_price")]
            public float Unit_price { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"discount_percentage")]
            public float Discount_percentage { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"total_sales")]
            public float Total_sales { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SalesModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"sale_id")]
            public float Sale_id { get; set; }

            [ColumnName(@"sale_date")]
            public float[] Sale_date { get; set; }

            [ColumnName(@"year_number")]
            public float Year_number { get; set; }

            [ColumnName(@"month_number")]
            public float Month_number { get; set; }

            [ColumnName(@"day_number")]
            public float Day_number { get; set; }

            [ColumnName(@"day_of_week")]
            public float Day_of_week { get; set; }

            [ColumnName(@"customer_code")]
            public float[] Customer_code { get; set; }

            [ColumnName(@"customer_name")]
            public float[] Customer_name { get; set; }

            [ColumnName(@"product_code")]
            public float[] Product_code { get; set; }

            [ColumnName(@"product_name")]
            public float[] Product_name { get; set; }

            [ColumnName(@"category_name")]
            public float[] Category_name { get; set; }

            [ColumnName(@"zone_name")]
            public float[] Zone_name { get; set; }

            [ColumnName(@"salesman_name")]
            public float[] Salesman_name { get; set; }

            [ColumnName(@"warehouse_name")]
            public float[] Warehouse_name { get; set; }

            [ColumnName(@"quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"unit_price")]
            public float Unit_price { get; set; }

            [ColumnName(@"discount_percentage")]
            public float Discount_percentage { get; set; }

            [ColumnName(@"total_sales")]
            public float Total_sales { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SalesModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
